plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // JUnit test framework.
    testImplementation libs.junit
    testImplementation "org.assertj:assertj-core:3.11.1"

    // Testing with SQLite
    implementation "org.xerial:sqlite-jdbc:3.44.1.0"
    implementation "org.jdbi:jdbi3-sqlite:3.45.0"

    // MySQL/MariaDb (houd deze voor andere mogelijke databases)
    implementation 'mysql:mysql-connector-java:5.1.6'

    // JDBI
    implementation 'org.jdbi:jdbi3-core:3.45.0'
    implementation 'org.jdbi:jdbi3-sqlobject:3.45.0'

    // JPA
    implementation 'org.hibernate:hibernate-core:5.6.15.Final'  // Hibernate core voor JPA
    implementation 'javax.persistence:javax.persistence-api:2.2'  // JPA API

    // Guava voor algemene gebruik
    implementation libs.guava

    // Database afhankelijkheden (H2 voor testen)
    runtimeOnly 'com.h2database:h2:1.4.200'  // Voeg deze regel toe voor de H2 database

    // Eventuele andere benodigde dependencies
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

run {
    standardInput = System.in
}

application {
    // Define the main class for the application.
    mainClass = 'be.kuleuven.App'
}
